microservice:
  citizen-service:
    endpoints:
      endpoint:
        uri: http://CITIZEN-SERVICE/citizen/id/
  VaccinationCenter-service:
    endpoints:
      endpoint:
        uri: http://VACCINATION-CENTER-SERVICE/vaccinationcenter/id/  
