eureka:
  client:
    register-with-eureka: true
    fetch-registry:  true
  instance:
    hostname: localhost
  service-url:
    default-zone: http://localhost:8761/eureka
    
 microservice:
  payment-service:
    endpoints:
      endpoint:
        uri: http://PAYMENT-SERVICE/payment/doPayment
  order-service:
    endpoints:
      endpoint:
        uri: http://ORDER-SERVICE/order/bookOrder  
